version: "3"

services:
  tests:
    container_name: composed-tests
    image: maven:latest
    environment:
      - TZ=America/New_York
    depends_on:
      - selenoid
      - selenoid-ui
    working_dir: /usr/src/mymaven
    network_mode: bridge
    links:
      - selenoid
    volumes:
      - "$PWD:/usr/src/mymaven"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/.m2:/root/.m2"
